services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_otp
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
      dockerfile: cmd/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - PORT=8080
      - SECRET=24vm89v5y7q-x,m349ci-143-v5um120-5v27n45-1237cn4
      - SQLDB=host=db user=postgres password=postgres dbname=user_otp port=5432 sslmode=disable TimeZone=Asia/Tehran
      - RedisServer=redis:6379
      - RedisPass=
      - DEBUG=false
      - KAVENEGAR_KEY=5839485A61777959584833643366417072545A7A49614B4942426B304B7A5176776245356478394A5936593D
      - KAVENEGAR_SENDER=

volumes:
  db-data:
  redis-data:
