info:
  contact: {}
paths:
  /hello:
    get:
      description: Returns Hello World message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Say Hello
      tags:
      - example
swagger: "2.0"
